version: "3"

services:
  foxlink-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    tty: True
    env_file:
      - .env
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=foxlink
      - FOXLINK_EVENT_DB_HOSTS=['172.168.1.231:3306']
      - FOXLINK_EVENT_DB_USER=ntust2
      - FOXLINK_EVENT_DB_PWD=ntust2pwd
      - FOXLINK_EVENT_DB_NAME=['aoi']
      - FOXLINK_DEVICE_DB_HOST=172.168.1.231:3306
      - FOXLINK_DEVICE_DB_USER=ntust2
      - FOXLINK_DEVICE_DB_PWD=ntust2pwd
      - ACCESS_LOG=logs/access.log
      - ERROR_LOG=logs/error.log
      - LOG_LEVEL=debug
    restart: unless-stopped
    ports:
      - 19001:80
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - .:/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      MYSQL_DATABASE: foxlink
      MYSQL_ROOT_PASSWORD: AqqhQ993VNto
    ports:
      - 27001:3306
    volumes:
      - mysql-db1:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-db1:
