"""Update devices table-2

Revision ID: 18ba6992bea1
Revises: a8c3e67165c5
Create Date: 2024-05-04 08:27:06.070110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18ba6992bea1'
down_revision = 'a8c3e67165c5'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_job_next_run_time', table_name='job')
    # op.drop_table('job')
     op.alter_column('devices', 'start_date', nullable=True, type_=sa.Date())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'start_date')
    # ### end Alembic commands ###