"""Add start_date column to Device table

Revision ID: 74399994a1a3
Revises: 5e0952bd163e
Create Date: 2024-05-04 08:04:49.193224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74399994a1a3'
down_revision = '5e0952bd163e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_job_next_run_time', table_name='job')
    # op.drop_table('job')
    op.add_column('devices', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'start_date')
    # ### end Alembic commands ###
