"""Update devices table

Revision ID: a8c3e67165c5
Revises: 74399994a1a3
Create Date: 2024-05-04 08:20:57.736838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8c3e67165c5'
down_revision = '74399994a1a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('devices', 'start_date', nullable=False, type_=sa.Date())

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'start_date')
    # ### end Alembic commands ###
