"""Add new field

Revision ID: afddbd6e5fec
Revises: 76c44ab22fe3
Create Date: 2024-05-17 11:13:02.319350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afddbd6e5fec'
down_revision = '76c44ab22fe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('level', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    
    # ### end Alembic commands ###
