"""update

Revision ID: ef3fdff1bfa3
Revises: d1c6270ca171
Create Date: 2022-12-11 02:24:30.985227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef3fdff1bfa3'
down_revision = 'd1c6270ca171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_log_headers_user'), 'audit_log_headers', ['user'], unique=False)
    op.drop_constraint('fk_audit_log_headers_users_badge_user', 'audit_log_headers', type_='foreignkey')
    op.alter_column('devices', 'workshop',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('missions', 'device',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('missions', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('missions', 'device',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('devices', 'workshop',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_audit_log_headers_users_badge_user', 'audit_log_headers', 'users', ['user'], ['badge'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_log_headers_user'), table_name='audit_log_headers')
    # ### end Alembic commands ###
